name: .NET Core

on: push

# vm contents
# https://github.com/actions/virtual-environments/tree/main/images/linux

# shell notes
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell

# default env vars:
# https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
    - name: dotnet clean
      run: |  
          cd "Riskified.SDK"
          dotnet clean
    - name: dotnet build
      run: |
          cd "Riskified.SDK"
          $branch = @($env:GITHUB_REF -split "/")[-1]
          $runNumber = $env:GITHUB_RUN_NUMBER
          if($branch -eq "master")
          {
            dotnet build --configuration Release --version-suffix $runNumber
            dotnet pack --no-build --configuration Release --version-suffix $runNumber -o out
          }else {
            dotnet build --configuration Release --version-suffix "$branch$runNumber"
            dotnet pack --no-build --configuration Release --version-suffix "$branch$runNumber" -o out
          }
      shell: pwsh
    - name: publish to nuget
      run: | 
          dotnet nuget push ./Riskified.SDK/out/*.nupkg -k ${{ secrets.Nuget_tristan }} -s https://api.nuget.org/v3/index.json
